species: arabidopsis
assembly: tair10
seq_info:
  type: BS-Seq
  mode: PE

path: /home/xfu/Project/Daisuke/Ros1/BS-Seq/fastq/

samples:
  - ros1_1
  - ros1_2
  - ros1_3
  - ros1_4
  - Col0_1
  - Col0_2
  - Col0_3
  - Col0_4

groups:
  - ros1_
  - Col0_

treatment:
  - 1
  - 1
  - 1
  - 1
  - 0
  - 0
  - 0
  - 0

win_size: 200

step_size: 50

cpu: 8

Rscript_path: /home/xfu/R/3.3.2/bin/Rscript

adapter: /home/xfu/miniconda2/envs/gmatic/share/trimmomatic/adapters/TruSeq3-PE-2.fa

genome_folder: /home/xfu/Gmatic5/genome/tair10/

IGV: /home/xfu/igv/genomes/tair10.genome

min_coverage: 4

fisher_test:
  treat: ros1_
  ctrl: Col0_

fold_change: 1.5
